### ISSUE TITLE
Flow bit_rate

### ISSUE THREAD

**Issue by alabou** [AMWA-TV/bcp-006-01#13]
The Flow bit_rate property links to [Bit Rate](https://specs.amwa.tv/nmos-parameter-registers/branches/main/flow-attributes/#bit-rate) which is described for jxsv as including IP headers,etc ... 

Maybe the description of [Bit Rate](https://specs.amwa.tv/nmos-parameter-registers/branches/main/flow-attributes/#bit-rate) must define it in the context of Flow and Sender property/capability ...

SORRY, this is probably a non-issue as we are still in a dev branch.

**Comment by garethsb** [comment]
It's just in the other branch as not merged yet -
https://specs.amwa.tv/nmos-parameter-registers/branches/publish-level-sublevel_bpp/flow-attributes/#bit-rate
(vs.
https://specs.amwa.tv/nmos-parameter-registers/branches/publish-level-sublevel_bpp/sender-attributes/#bit-rate
)
