### ISSUE TITLE
Clearly state Controller requirements?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/bcp-006-01#20]
At the moment, BCP-006-01 draft focuses on the requirements on Nodes that transmit or receive JPEG XS streams.
This includes making REQUIRED all the Flow and Sender attributes, and Receiver parameter constraints, that enable a Controller to ascertain whether those Senders and Receivers are compatible.

We've learnt from the Controller spec activity (viz. recent INFO-005 and IS-04, IS-05 and BCP-003-01 updates) that we need to bring together and clearly state requirements for Controllers too.

Seems like we could add a Controllers sub-heading, and e.g. state that a Controller MUST be capable of using these Flow/Sender attributes and Receiver caps to determine compatibility?

**Comment by pedro-alves-ferreira** [comment]
Yes, I think we should always provide that information in any spec which implies the existence of a controller.

**Comment by garethsb** [comment]
Resolved by #21
