### ISSUE TITLE
SDP File TP Value.

### ISSUE THREAD

**Issue by rbgodwin-nt** [AMWA-TV/bcp-006-01#22]
The Example SDP file uses TP=2110TPN while SMPTE2110-22 states the value should be either 2110TPNL or 2110TPW.

https://github.com/AMWA-TV/bcp-006-01/blob/v1.0-dev/examples/jpeg-xs.sdp

**Comment by garethsb** [comment]
![ST2110-22:2022 Section 5.3](https://user-images.githubusercontent.com/31761158/204080378-46d90d0d-e300-4483-89a5-06503c21b411.jpg)

**Comment by rbgodwin** [comment]
Looks good.  I was referencing 2110-22:2019 (looks like I missed the update that came out in September). No other changes it seems so I've updated the test and commited to check for the correct items for Traffic shaping

**Comment by rbgodwin-nt** [comment]
Looks good. I was referencing 2110-22:2019 (looks like I missed the update that came out in September). No other changes it seems so I've updated the sdpoker test and commited to check for the correct items for Traffic shaping. Closing this issue. Thanks!

**Comment by garethsb** [comment]
Hmm... you could argue that although `SSN` values for ST 2110-22 were only introduced in the 2022 revision, putting `TP=2110TPN` alongside `SSN=ST2110-22:2019` looks a bit odd given that the bug fix to allow Type N is in the 2022 revision...
