### ISSUE TITLE
Bit rate in Flow and SDP

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/bcp-006-01#6]
The Flows section currently says:

> Nodes implementing IS-04 v1.3 or higher MUST indicate the stream bit rate in the Flow resource using the `bit_rate` attribute also defined in the Flow Attributes register.
> The bit rate value also appears in the SDP file, per RFC 9134.

In fact, putting the bit rate value in the SDP file using the `b=AS:` application-specific bandwidth line is a requirement of ST 2110-22 (and VSF TR-08), _not_ RFC 9134. So, should the the requirement of the first sentence above be predicated on the Node trying to conform with ST 2110-22?

**Comment by jmailhot** [comment]
bit_rate is pretty helpful as a property of the flow.  but yes, the second sentence about where it appears should say "per SMPTE ST 2110-22".  the IETF was/is pretty inconsistent in how it represents rate in SDP so in 2110-22 we tried to pick one.

**Comment by garethsb** [comment]
Thanks, @jmailhot, completely agree the definition in ST 2110-22 is much more useful than what's in RFC 4566.

On a related note, you mentioned VSF TR-08 would be revised. In order to make the mapping from its Appendix B interoperability sets to BCP-004-01 constraint sets as transparent as possible, would it be a good idea if the min/max bit rate columns in that appendix were in the same units (kb/s)?

**Comment by jmailhot** [comment]
in the jpeg-xs community, typically the rate is specified in bits-per-pixel, and likewise the constraints are really in BPP.  translating BPP to an actual kbits/sec value is slightly tricky unless its super well defined what is included or not.  (UDP, IP, ETH, MAC, ...)

**Comment by garethsb** [comment]
The meaning of `bit_rate` is well defined here though, it includes RTP payload down to IP, but not ETH or lower.

If mapping bpp to that bit rate is too tricky, should we add a JPEG XS-specific parameter constraint (and Flow attribute...) on bpp directly?

**Comment by garethsb** [comment]
> The meaning of `bit_rate` is well defined here though, it includes RTP payload down to IP, but not ETH or lower.
> 
> If mapping bpp to that bit rate is too tricky, should we add a JPEG XS-specific parameter constraint (and Flow attribute...) on bpp directly?

@jmailhot, @peterbrightwell, I found an interesting recent RFC - [RFC 8851](https://www.rfc-editor.org/rfc/rfc8851.html#name-arid-restrictions) - that defines a framework and extensible IANA register for specifying restrictions on RTP streams.

Its initial set of video-focused but codec-agnostic restrictions include **max-br** (maximum bit rate, as b/s*), **max-width** and **max-height** and also **max-bpp**.

It comes down to how people/systems really want to express themselves. If a Receiver's criteria for accepting a stream are really based on "bits per pixel", then the bit rate is a poor parameter constraint to use, because it means you need a different value for each frame rate/width/height combo, even ignoring the problem with packetization overhead.

*Unlike ST 2110-22 definition of bit rate, **max-br** applies to the media payload only and does not include overhead introduced by other layers (e.g., RTP, UDP, IP, or Ethernet)

**Comment by rbgodwin-nt** [comment]
I believe the VSF groups are more familiar with the Bits-per-pixel but from an implementor's standpoint I  would like to have this expressed as an independent bits-per-pixel capability of a NMOS device's receivers.  We have some systems that are limited to a certain range of bit-per-pixel forJPEG-XS so a receiver constraint seems like a good fit to capture this. I think I also heard that NDI had specific values for BPP(so enums).    Some JPEG-XS licenses also limit the values so likely we will see a range of receiver caps for different BPPs constraints.

With the BPP constraints called out, controllers would then be able to include business logic that choses the sender format based on the BPPs capabilities of the target receivers.  This is very similar to one or two of the user-stories for IS-11 that decides best common video resolution for a group of HDMI displays.

**Comment by garethsb** [comment]
Input from Jean-Baptiste Lorent and Tim Bruylants (@tbr) intoPIX, 9 Feb 2022, has bearing on this issue and also #10, #11, etc.

[nmos_xs.pdf](https://github.com/AMWA-TV/bcp-006-01/files/8621164/nmos_xs.pdf)

**Comment by rbgodwin** [comment]
The pdf from Jean-Baptiste and Tim is helpful but still seems to me there could be value in calling out the bpp capabilities of a encoder/decoder. In particular I could see a situation were we have a decoder to supports one of the profiles such as those listed in the pdf but due to it's own internal implementation limitations or marketing from the vender providing limited capabilities for lower end devices would only provide visually lossless for one of it's devices and not full lossless as set by bpp.  This could show up as exposing particular profiles supported along with a range or enum of bpp supported,  Just a thought and might be overcomplicating it.  Perhaps the profile itself has the bpp called out as a range?  Do we have any detailed profiles for the several listed in the pdf?

**Comment by garethsb** [comment]
Thanks, Randy. I think the solution we've agreed in the last Activity Group call, that we define `sublevel_bpp` as a numerical parameter and thus receptive to constraint by min/max, handles this use case. I will prepare new pull requests this week. By the way, Tim has updated the Wikipedia page for [JPEG XS: Profiles, levels and sublevels](https://en.m.wikipedia.org/wiki/JPEG_XS#Profiles,_levels_and_sublevels).

Unlike `profile` and `level` string parameters which the group intends to be usable for many formats, with enumerated values per `media_type`, the `sublevel_bpp` may well only be applicable to JPEG XS.

**Comment by garethsb** [comment]
Will be resolved by #12.

**Comment by garethsb** [comment]
We've now gone back to string enum `sublevel`, e.g. Receiver cap of `"enum": [ "Sublev3bpp", "Sublev4bpp" ]` might be common. But I think most use cases @rbgodwin described are still handled by that, and the others, slightly less successfully, can be handled by format `bit_rate` constraint, so I think this issue can still be closed when #12 is merged.

**Comment by rbgodwin** [comment]
Sublevels for bpp with enums look good to me and tying them into the documentation on JPEG-XS makes good sense to me.  So if a sender or receiver has a range then can simply call out the sublevel bpps supported.  Great!
