### ISSUE TITLE
Add example SDP file

### ISSUE THREAD

**Issue by peterbrightwell** [AMWA-TV/bcp-006-01#8]
As discussed on Incubator 2021-12-08: This referenced in the document but doesn't yet exist.

**Comment by garethsb** [comment]
It does exist, the doc build scripts just omit it. https://github.com/AMWA-TV/nmos-doc-build-scripts/issues/46

**Comment by garethsb** [comment]
@rmsporter pointed out that the [examples/jpeg-xs.sdp](https://github.com/AMWA-TV/bcp-006-01/blob/4027520fbb31d5a16c03963de8af8f8c97d66add/examples/jpeg-xs.sdp) SDP file is currently missing the bandwidth `b=AS:` line required by ST 2110-22. @jmailhot, can you provide this for the example?

**Comment by garethsb** [comment]
Can we use the example from [VSF_TR-08_2022-04-20.pdf](https://vsf.tv/download/technical_recommendations/VSF_TR-08_2022-04-20.pdf) (once the `b=` problem is fixed)?

**Comment by garethsb** [comment]
Will be resolved by #12.

**Comment by garethsb** [comment]
Resolved by #12 and AMWA-TV/nmos-render-scripts/pull/53.
