### ISSUE TITLE
RFC 9134 Version Support

### ISSUE THREAD

**Issue by rbgodwin-nt** [AMWA-TV/bcp-006-01#9]
We recently ran into a case where we two venders with correct implementation of different versions of RFC-9134 (https://datatracker.ietf.org/doc/html/draft-ietf-payload-rtp-jpegxs-18) did not opererate together.  Since the JPEG-XS specification for packetization is evolving does it make some sense to put into the receiver caps and parameters the specific range or specific values for RFC 9134 version supported by a receiver? 

The controller could then "reason" about what common format spans the target receivers and adjust to send that version of packetization with the SDP file containing the specific version of JPEG-XS packetization employed.  This would give us maximum flexibility for supporting a wide range of hardware. 

Thoughts?

**Comment by garethsb** [comment]
Tbh, I would rather focus on the already published RFC and assume here that implementations of outdated drafts will be fixed to conform to the final spec.

**Comment by rbgodwin-nt** [comment]
Is there such a thing though as a final spec for these new media types? Looking over NDI I see there are currently 12 versions over the last 6 years with major and minor versions (https://en.wikipedia.org/wiki/Network_Device_Interface).    I suspect we will see improvements in each of these new media types that can introduce confusion for operators trying to connect incompatible equipment that say "JPEG-XS" capable. Having the vender's that produce JPEG-XS equipment with NMOS capabilities put explicitly in their receiver capabilities the versions supported could be useful.

**Comment by jmailhot** [comment]
Can’t speak for NDI, but once an RFC is published it is done.  Errata can
be filed (9134 has an errata already) but no real changes.

Yes some people built to early drafts, and they need to update their
products - we also run into this case in the field and it’s a problem.

**Comment by tbr** [comment]
Creating an RFC takes many steps, and always starts with drafts. These drafts are versioned, but are in itself never approved RFC's. Vendors often start implementations, based on a draft RFC, but need to update their implementations once the final RFC is published.

What is more, once an RFC is published, it can and will never be changed again (not even to fix a typo). So, in my opinion, there is no use in adding version support for RFC 9134. The RFC itself is the version. If updates to the specification are needed, the new version will also be a different RFC.

**Comment by garethsb** [comment]
Closed per discussion in activity group, 18 May 2022
